# Generated by Django 4.2 on 2025-07-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_review_options_alter_offer_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
